### PR TITLE
Check whether the path given is absent in the PATH

### PR DESCRIPTION
**Pull request by sergeyklay**
Should generate something like that

```sh
# DO NOT EDIT: installed by update-golang.sh

if ! echo "$PATH" | grep -Eq "(^|:)/usr/local/go/bin($|:)"
then
    export PATH=$PATH:/usr/local/go/bin
fi

if ! echo "$PATH" | grep -Eq "(^|:)$HOME/go/bin($|:)"
then
    export PATH=$PATH:$HOME/go/bin
fi

# update-golang.sh: end
```

### CODE REVIEW

**Comment by sergeyklay** [comment]
@udhos Could you please take a look

**Comment by udhos** [comment]
As it is now, this change breaks profile_path_remove().

**Comment by udhos** [comment]
Hi, do you intend to modify the change to support profile_path_remove() ?

**Comment by sergeyklay** [comment]
@udhos I'll try in next days. Do you want to do it yourself?

**Comment by udhos** [comment]
Great, please feel free to modify the change if you can. I won't be able to look into it myself in the next days.

**Comment by sergeyklay** [comment]
@udhos I hope it is ok now

**Comment by udhos** [comment]
It is a great improvement, thanks.

However I think the change is missing the code to append `/# $path_mark: end/`, no?

`sed "/# DO NOT EDIT: installed by $path_mark/,/# $path_mark: end/d" "$abs_profiled" > "$tmp"`

**Comment by sergeyklay** [comment]
@udhos This is weird. I remember writing it. Probably I lost at the rebase time. I apologize for the inconvenience.

**Comment by udhos** [comment]
Merged, thanks!

**Comment by sergeyklay** [comment]
You're welcome

**Pull request merged**
